-- begin KINDERKANKERFONDS_ADRES
alter table KINDERKANKERFONDS_ADRES add constraint FK_KINDERKANKERFONDS_ADRES_ON_PERSOON foreign key (PERSOON_ID) references KINDERKANKERFONDS_PERSOON(ID)^
alter table KINDERKANKERFONDS_ADRES add constraint FK_KINDERKANKERFONDS_ADRES_ON_TYPE foreign key (TYPE_ID) references KINDERKANKERFONDS_ADRES_TYPE(ID)^
create index IDX_KINDERKANKERFONDS_ADRES_ON_PERSOON on KINDERKANKERFONDS_ADRES (PERSOON_ID)^
create index IDX_KINDERKANKERFONDS_ADRES_ON_TYPE on KINDERKANKERFONDS_ADRES (TYPE_ID)^
-- end KINDERKANKERFONDS_ADRES
