-- begin KINDERKANKERFONDS_ADRES
alter table KINDERKANKERFONDS_ADRES add constraint FK_KINDERKANKERFONDS_ADRES_ON_PERSOON foreign key (PERSOON_ID) references KINDERKANKERFONDS_PERSOON(ID)^
alter table KINDERKANKERFONDS_ADRES add constraint FK_KINDERKANKERFONDS_ADRES_ON_TYPE foreign key (TYPE_ID) references KINDERKANKERFONDS_ADRES_TYPE(ID)^
create index IDX_KINDERKANKERFONDS_ADRES_ON_PERSOON on KINDERKANKERFONDS_ADRES (PERSOON_ID)^
create index IDX_KINDERKANKERFONDS_ADRES_ON_TYPE on KINDERKANKERFONDS_ADRES (TYPE_ID)^
-- end KINDERKANKERFONDS_ADRES
-- begin KINDERKANKERFONDS_GESLACHT
create unique index IDX_KINDERKANKERFONDS_GESLACHT_UNIQ_NAAM on KINDERKANKERFONDS_GESLACHT (NAAM) ^
-- end KINDERKANKERFONDS_GESLACHT
-- begin KINDERKANKERFONDS_RELATIE
alter table KINDERKANKERFONDS_RELATIE add constraint FK_KINDERKANKERFONDS_RELATIE_ON_TYPE foreign key (TYPE_ID) references KINDERKANKERFONDS_RELATIE_TYPE(ID)^
create index IDX_KINDERKANKERFONDS_RELATIE_ON_TYPE on KINDERKANKERFONDS_RELATIE (TYPE_ID)^
-- end KINDERKANKERFONDS_RELATIE
-- begin KINDERKANKERFONDS_PERSOON
alter table KINDERKANKERFONDS_PERSOON add constraint FK_KINDERKANKERFONDS_PERSOON_ON_GESLACHT foreign key (GESLACHT_ID) references KINDERKANKERFONDS_GESLACHT(ID)^
create index IDX_KINDERKANKERFONDS_PERSOON_ON_GESLACHT on KINDERKANKERFONDS_PERSOON (GESLACHT_ID)^
-- end KINDERKANKERFONDS_PERSOON
