alter table KINDERKANKERFONDS_PERSOON_PERSOON_LINK add constraint FK_PERPER_ON_PERSOON_1 foreign key (PERSOON_1_ID) references KINDERKANKERFONDS_PERSOON(ID);
alter table KINDERKANKERFONDS_PERSOON_PERSOON_LINK add constraint FK_PERPER_ON_PERSOON_2 foreign key (PERSOON_2_ID) references KINDERKANKERFONDS_PERSOON(ID);
