alter table KINDERKANKERFONDS_ADRES add constraint FK_KINDERKANKERFONDS_ADRES_ON_LAND foreign key (LAND_ID) references KINDERKANKERFONDS_LAND(ID);
create index IDX_KINDERKANKERFONDS_ADRES_ON_LAND on KINDERKANKERFONDS_ADRES (LAND_ID);
