alter table KINDERKANKERFONDS_NOTITIE add constraint FK_KINDERKANKERFONDS_NOTITIE_ON_ADRES foreign key (ADRES_ID) references KINDERKANKERFONDS_ADRES(ID);
create index IDX_KINDERKANKERFONDS_NOTITIE_ON_ADRES on KINDERKANKERFONDS_NOTITIE (ADRES_ID);
