alter table KINDERKANKERFONDS_ADRES_CATEGORIE_LINK add constraint FK_ADRCAT_ON_ADRES foreign key (ADRES_ID) references KINDERKANKERFONDS_ADRES(ID);
alter table KINDERKANKERFONDS_ADRES_CATEGORIE_LINK add constraint FK_ADRCAT_ON_CATEGORIE foreign key (CATEGORIE_ID) references KINDERKANKERFONDS_CATEGORIE(ID);
