alter table DDCT_TAGGING add constraint FK_DDCT_TAGGING_ON_PERSOON foreign key (PERSOON_ID) references KINDERKANKERFONDS_PERSOON(ID);
create index IDX_DDCT_TAGGING_ON_PERSOON on DDCT_TAGGING (PERSOON_ID);
