alter table KINDERKANKERFONDS_PERSOON_RELATIE_LINK add constraint FK_PERREL_ON_RELATIE foreign key (RELATIE_ID) references KINDERKANKERFONDS_RELATIE(ID);
alter table KINDERKANKERFONDS_PERSOON_RELATIE_LINK add constraint FK_PERREL_ON_PERSOON foreign key (PERSOON_ID) references KINDERKANKERFONDS_PERSOON(ID);
