alter table KINDERKANKERFONDS_PERSOON add column STUDIO_NONA boolean ;
alter table KINDERKANKERFONDS_PERSOON add column KOESTER_NIET_ONCO boolean ;
alter table KINDERKANKERFONDS_PERSOON add column RESIDENTIE_KOESTER boolean ;
