-- begin KINDERKANKERFONDS_PERSOON
alter table KINDERKANKERFONDS_PERSOON add constraint FK_KINDERKANKERFONDS_PERSOON_GESLACHT foreign key (GESLACHT_ID) references KINDERKANKERFONDS_GESLACHT(ID)^
alter table KINDERKANKERFONDS_PERSOON add constraint FK_KINDERKANKERFONDS_PERSOON_ZIEKENHUIS foreign key (ZIEKENHUIS_ID) references KINDERKANKERFONDS_ZIEKENHUIS(ID)^
create unique index IDX_KINDERKANKERFONDS_PERSOON_UK_UNIEKEID on KINDERKANKERFONDS_PERSOON (UNIEKEID) where DELETE_TS is null ^
create index IDX_KINDERKANKERFONDS_PERSOON_GESLACHT on KINDERKANKERFONDS_PERSOON (GESLACHT_ID)^
create index IDX_KINDERKANKERFONDS_PERSOON_ZIEKENHUIS on KINDERKANKERFONDS_PERSOON (ZIEKENHUIS_ID)^
-- end KINDERKANKERFONDS_PERSOON
-- begin KINDERKANKERFONDS_ADRES
alter table KINDERKANKERFONDS_ADRES add constraint FK_KINDERKANKERFONDS_ADRES_LAND foreign key (LAND_ID) references KINDERKANKERFONDS_LAND(ID)^
alter table KINDERKANKERFONDS_ADRES add constraint FK_KINDERKANKERFONDS_ADRES_PERSOON foreign key (PERSOON_ID) references KINDERKANKERFONDS_PERSOON(ID)^
alter table KINDERKANKERFONDS_ADRES add constraint FK_KINDERKANKERFONDS_ADRES_TYPE foreign key (TYPE_ID) references KINDERKANKERFONDS_ADRES_TYPE(ID)^
create index IDX_KINDERKANKERFONDS_ADRES_LAND on KINDERKANKERFONDS_ADRES (LAND_ID)^
create index IDX_KINDERKANKERFONDS_ADRES_PERSOON on KINDERKANKERFONDS_ADRES (PERSOON_ID)^
create index IDX_KINDERKANKERFONDS_ADRES_TYPE on KINDERKANKERFONDS_ADRES (TYPE_ID)^
-- end KINDERKANKERFONDS_ADRES

-- begin KINDERKANKERFONDS_RELATIE
alter table KINDERKANKERFONDS_RELATIE add constraint FK_KINDERKANKERFONDS_RELATIE_TYPE foreign key (TYPE_ID) references KINDERKANKERFONDS_RELATIE_TYPE(ID)^
alter table KINDERKANKERFONDS_RELATIE add constraint FK_KINDERKANKERFONDS_RELATIE_PERSOON_ORIGINE foreign key (PERSOON_ORIGINE_ID) references KINDERKANKERFONDS_PERSOON(ID)^
alter table KINDERKANKERFONDS_RELATIE add constraint FK_KINDERKANKERFONDS_RELATIE_PERSOON_DOEL foreign key (PERSOON_DOEL_ID) references KINDERKANKERFONDS_PERSOON(ID)^
create index IDX_KINDERKANKERFONDS_RELATIE_TYPE on KINDERKANKERFONDS_RELATIE (TYPE_ID)^
create index IDX_KINDERKANKERFONDS_RELATIE_PERSOON_ORIGINE on KINDERKANKERFONDS_RELATIE (PERSOON_ORIGINE_ID)^
create index IDX_KINDERKANKERFONDS_RELATIE_PERSOON_DOEL on KINDERKANKERFONDS_RELATIE (PERSOON_DOEL_ID)^
-- end KINDERKANKERFONDS_RELATIE
-- begin KINDERKANKERFONDS_ZIEKENHUIS
alter table KINDERKANKERFONDS_ZIEKENHUIS add constraint FK_KINDERKANKERFONDS_ZIEKENHUIS_ADRES foreign key (ADRES_ID) references KINDERKANKERFONDS_ADRES(ID)^
-- end KINDERKANKERFONDS_ZIEKENHUIS
-- begin KINDERKANKERFONDS_CONTACT_INFO
alter table KINDERKANKERFONDS_CONTACT_INFO add constraint FK_KINDERKANKERFONDS_CONTACT_INFO_PERSOON foreign key (PERSOON_ID) references KINDERKANKERFONDS_PERSOON(ID)^
create index IDX_KINDERKANKERFONDS_CONTACT_INFO_PERSOON on KINDERKANKERFONDS_CONTACT_INFO (PERSOON_ID)^
-- end KINDERKANKERFONDS_CONTACT_INFO
-- begin KINDERKANKERFONDS_NOTITIE
alter table KINDERKANKERFONDS_NOTITIE add constraint FK_KINDERKANKERFONDS_NOTITIE_ADRESSEN foreign key (ADRESSEN_ID) references KINDERKANKERFONDS_ADRES(ID)^
alter table KINDERKANKERFONDS_NOTITIE add constraint FK_KINDERKANKERFONDS_NOTITIE_ZIEKENHUIS foreign key (ZIEKENHUIS_ID) references KINDERKANKERFONDS_ZIEKENHUIS(ID)^
alter table KINDERKANKERFONDS_NOTITIE add constraint FK_KINDERKANKERFONDS_NOTITIE_CONTACTINFO foreign key (CONTACTINFO_ID) references KINDERKANKERFONDS_CONTACT_INFO(ID)^
alter table KINDERKANKERFONDS_NOTITIE add constraint FK_KINDERKANKERFONDS_NOTITIE_PERSOON foreign key (PERSOON_ID) references KINDERKANKERFONDS_PERSOON(ID)^
alter table KINDERKANKERFONDS_NOTITIE add constraint FK_KINDERKANKERFONDS_NOTITIE_AFSPRAAK foreign key (AFSPRAAK_ID) references KINDERKANKERFONDS_AFSPRAAK(ID)^
create index IDX_KINDERKANKERFONDS_NOTITIE_ADRESSEN on KINDERKANKERFONDS_NOTITIE (ADRESSEN_ID)^
create index IDX_KINDERKANKERFONDS_NOTITIE_ZIEKENHUIS on KINDERKANKERFONDS_NOTITIE (ZIEKENHUIS_ID)^
create index IDX_KINDERKANKERFONDS_NOTITIE_CONTACTINFO on KINDERKANKERFONDS_NOTITIE (CONTACTINFO_ID)^
create index IDX_KINDERKANKERFONDS_NOTITIE_PERSOON on KINDERKANKERFONDS_NOTITIE (PERSOON_ID)^
create index IDX_KINDERKANKERFONDS_NOTITIE_AFSPRAAK on KINDERKANKERFONDS_NOTITIE (AFSPRAAK_ID)^
-- end KINDERKANKERFONDS_NOTITIE
-- begin KINDERKANKERFONDS_PERSOON_CATEGORIE_LINK
alter table KINDERKANKERFONDS_PERSOON_CATEGORIE_LINK add constraint FK_PERCAT_ON_CATEGORIE foreign key (CATEGORIE_ID) references KINDERKANKERFONDS_CATEGORIE(ID)^
alter table KINDERKANKERFONDS_PERSOON_CATEGORIE_LINK add constraint FK_PERCAT_ON_PERSOON foreign key (PERSOON_ID) references KINDERKANKERFONDS_PERSOON(ID)^
-- end KINDERKANKERFONDS_PERSOON_CATEGORIE_LINK
-- begin KINDERKANKERFONDS_ADRES_CATEGORIE_LINK
alter table KINDERKANKERFONDS_ADRES_CATEGORIE_LINK add constraint FK_ADRCAT_ON_ADRES foreign key (ADRES_ID) references KINDERKANKERFONDS_ADRES(ID)^
alter table KINDERKANKERFONDS_ADRES_CATEGORIE_LINK add constraint FK_ADRCAT_ON_CATEGORIE foreign key (CATEGORIE_ID) references KINDERKANKERFONDS_CATEGORIE(ID)^
-- end KINDERKANKERFONDS_ADRES_CATEGORIE_LINK
-- begin KINDERKANKERFONDS_AFSPRAAK
alter table KINDERKANKERFONDS_AFSPRAAK add constraint FK_KINDERKANKERFONDS_AFSPRAAK_PERSOON foreign key (PERSOON_ID) references KINDERKANKERFONDS_PERSOON(ID)^
alter table KINDERKANKERFONDS_AFSPRAAK add constraint FK_KINDERKANKERFONDS_AFSPRAAK_AFDELING foreign key (AFDELING_ID) references KINDERKANKERFONDS_AFDELING(ID)^
alter table KINDERKANKERFONDS_AFSPRAAK add constraint FK_KINDERKANKERFONDS_AFSPRAAK_KALENDER_KLEUR foreign key (KALENDER_KLEUR_ID) references KINDERKANKERFONDS_KALENDER_KLEUR(ID)^
create index IDX_KINDERKANKERFONDS_AFSPRAAK_PERSOON on KINDERKANKERFONDS_AFSPRAAK (PERSOON_ID)^
create index IDX_KINDERKANKERFONDS_AFSPRAAK_AFDELING on KINDERKANKERFONDS_AFSPRAAK (AFDELING_ID)^
create index IDX_KINDERKANKERFONDS_AFSPRAAK_KALENDER_KLEUR on KINDERKANKERFONDS_AFSPRAAK (KALENDER_KLEUR_ID)^
-- end KINDERKANKERFONDS_AFSPRAAK
