-- begin KINDERKANKERFONDS_PERSOON
alter table KINDERKANKERFONDS_PERSOON add constraint FK_KINDERKANKERFONDS_PERSOON_ON_GESLACHT foreign key (GESLACHT_ID) references KINDERKANKERFONDS_GESLACHT(ID)^
alter table KINDERKANKERFONDS_PERSOON add constraint FK_KINDERKANKERFONDS_PERSOON_ON_ZIEKENHUIS foreign key (ZIEKENHUIS_ID) references KINDERKANKERFONDS_ZIEKENHUIS(ID)^
create unique index IDX_KINDERKANKERFONDS_PERSOON_UK_UNIEKEID on KINDERKANKERFONDS_PERSOON (UNIEKEID) where DELETE_TS is null ^
create index IDX_KINDERKANKERFONDS_PERSOON_ON_GESLACHT on KINDERKANKERFONDS_PERSOON (GESLACHT_ID)^
create index IDX_KINDERKANKERFONDS_PERSOON_ON_ZIEKENHUIS on KINDERKANKERFONDS_PERSOON (ZIEKENHUIS_ID)^
-- end KINDERKANKERFONDS_PERSOON
-- begin KINDERKANKERFONDS_ADRES
alter table KINDERKANKERFONDS_ADRES add constraint FK_KINDERKANKERFONDS_ADRES_ON_LAND foreign key (LAND_ID) references KINDERKANKERFONDS_LAND(ID)^
alter table KINDERKANKERFONDS_ADRES add constraint FK_KINDERKANKERFONDS_ADRES_ON_PERSOON foreign key (PERSOON_ID) references KINDERKANKERFONDS_PERSOON(ID)^
alter table KINDERKANKERFONDS_ADRES add constraint FK_KINDERKANKERFONDS_ADRES_ON_TYPE foreign key (TYPE_ID) references KINDERKANKERFONDS_ADRES_TYPE(ID)^
create index IDX_KINDERKANKERFONDS_ADRES_ON_LAND on KINDERKANKERFONDS_ADRES (LAND_ID)^
create index IDX_KINDERKANKERFONDS_ADRES_ON_PERSOON on KINDERKANKERFONDS_ADRES (PERSOON_ID)^
create index IDX_KINDERKANKERFONDS_ADRES_ON_TYPE on KINDERKANKERFONDS_ADRES (TYPE_ID)^
-- end KINDERKANKERFONDS_ADRES
-- begin KINDERKANKERFONDS_GESLACHT
create unique index IDX_KINDERKANKERFONDS_GESLACHT_UK_NAAM on KINDERKANKERFONDS_GESLACHT (NAAM) where DELETE_TS is null ^
-- end KINDERKANKERFONDS_GESLACHT
-- begin KINDERKANKERFONDS_RELATIE
alter table KINDERKANKERFONDS_RELATIE add constraint FK_KINDERKANKERFONDS_RELATIE_ON_TYPE foreign key (TYPE_ID) references KINDERKANKERFONDS_RELATIE_TYPE(ID)^
alter table KINDERKANKERFONDS_RELATIE add constraint FK_KINDERKANKERFONDS_RELATIE_ON_PERSOON_ORIGINE foreign key (PERSOON_ORIGINE_ID) references KINDERKANKERFONDS_PERSOON(ID)^
alter table KINDERKANKERFONDS_RELATIE add constraint FK_KINDERKANKERFONDS_RELATIE_ON_PERSOON_DOEL foreign key (PERSOON_DOEL_ID) references KINDERKANKERFONDS_PERSOON(ID)^
create index IDX_KINDERKANKERFONDS_RELATIE_ON_TYPE on KINDERKANKERFONDS_RELATIE (TYPE_ID)^
create index IDX_KINDERKANKERFONDS_RELATIE_ON_PERSOON_ORIGINE on KINDERKANKERFONDS_RELATIE (PERSOON_ORIGINE_ID)^
create index IDX_KINDERKANKERFONDS_RELATIE_ON_PERSOON_DOEL on KINDERKANKERFONDS_RELATIE (PERSOON_DOEL_ID)^
-- end KINDERKANKERFONDS_RELATIE
-- begin KINDERKANKERFONDS_ZIEKENHUIS
alter table KINDERKANKERFONDS_ZIEKENHUIS add constraint FK_KINDERKANKERFONDS_ZIEKENHUIS_ON_ADRES foreign key (ADRES_ID) references KINDERKANKERFONDS_ADRES(ID)^
create index IDX_KINDERKANKERFONDS_ZIEKENHUIS_ON_ADRES on KINDERKANKERFONDS_ZIEKENHUIS (ADRES_ID)^
-- end KINDERKANKERFONDS_ZIEKENHUIS
-- begin KINDERKANKERFONDS_CONTACT_INFO
alter table KINDERKANKERFONDS_CONTACT_INFO add constraint FK_KINDERKANKERFONDS_CONTACT_INFO_ON_PERSOON foreign key (PERSOON_ID) references KINDERKANKERFONDS_PERSOON(ID)^
create index IDX_KINDERKANKERFONDS_CONTACT_INFO_ON_PERSOON on KINDERKANKERFONDS_CONTACT_INFO (PERSOON_ID)^
-- end KINDERKANKERFONDS_CONTACT_INFO
-- begin KINDERKANKERFONDS_NOTITIE
alter table KINDERKANKERFONDS_NOTITIE add constraint FK_KINDERKANKERFONDS_NOTITIE_ON_ADRESSEN foreign key (ADRESSEN_ID) references KINDERKANKERFONDS_ADRES(ID)^
alter table KINDERKANKERFONDS_NOTITIE add constraint FK_KINDERKANKERFONDS_NOTITIE_ON_ZIEKENHUIS foreign key (ZIEKENHUIS_ID) references KINDERKANKERFONDS_ZIEKENHUIS(ID)^
alter table KINDERKANKERFONDS_NOTITIE add constraint FK_KINDERKANKERFONDS_NOTITIE_ON_CONTACTINFO foreign key (CONTACTINFO_ID) references KINDERKANKERFONDS_CONTACT_INFO(ID)^
alter table KINDERKANKERFONDS_NOTITIE add constraint FK_KINDERKANKERFONDS_NOTITIE_ON_PERSOON foreign key (PERSOON_ID) references KINDERKANKERFONDS_PERSOON(ID)^
create index IDX_KINDERKANKERFONDS_NOTITIE_ON_ADRESSEN on KINDERKANKERFONDS_NOTITIE (ADRESSEN_ID)^
create index IDX_KINDERKANKERFONDS_NOTITIE_ON_ZIEKENHUIS on KINDERKANKERFONDS_NOTITIE (ZIEKENHUIS_ID)^
create index IDX_KINDERKANKERFONDS_NOTITIE_ON_CONTACTINFO on KINDERKANKERFONDS_NOTITIE (CONTACTINFO_ID)^
create index IDX_KINDERKANKERFONDS_NOTITIE_ON_PERSOON on KINDERKANKERFONDS_NOTITIE (PERSOON_ID)^
-- end KINDERKANKERFONDS_NOTITIE
-- begin KINDERKANKERFONDS_PERSOON_CATEGORIE_LINK
alter table KINDERKANKERFONDS_PERSOON_CATEGORIE_LINK add constraint FK_PERCAT_ON_CATEGORIE foreign key (CATEGORIE_ID) references KINDERKANKERFONDS_CATEGORIE(ID)^
alter table KINDERKANKERFONDS_PERSOON_CATEGORIE_LINK add constraint FK_PERCAT_ON_PERSOON foreign key (PERSOON_ID) references KINDERKANKERFONDS_PERSOON(ID)^
-- end KINDERKANKERFONDS_PERSOON_CATEGORIE_LINK
-- begin KINDERKANKERFONDS_ADRES_CATEGORIE_LINK
alter table KINDERKANKERFONDS_ADRES_CATEGORIE_LINK add constraint FK_ADRCAT_ON_ADRES foreign key (ADRES_ID) references KINDERKANKERFONDS_ADRES(ID)^
alter table KINDERKANKERFONDS_ADRES_CATEGORIE_LINK add constraint FK_ADRCAT_ON_CATEGORIE foreign key (CATEGORIE_ID) references KINDERKANKERFONDS_CATEGORIE(ID)^
-- end KINDERKANKERFONDS_ADRES_CATEGORIE_LINK
-- begin DDCT_TAGGING
alter table DDCT_TAGGING add constraint FK_DDCT_TAGGING_ON_PERSOON foreign key (PERSOON_ID) references KINDERKANKERFONDS_PERSOON(ID)^
create index IDX_DDCT_TAGGING_ON_PERSOON on DDCT_TAGGING (PERSOON_ID)^
-- end DDCT_TAGGING
